# config.yml

# DIRECTORY
DIR_LOG_DISCO: log_disco
DIR_LOG_DISCO_DURATION: log_disco_duration
DIR_LOG_ENCODED: log_encoded
DIR_LOG_INPUT: log_input # Directory with logs from which to derive prefixes 
DIR_LOG_NIRDIZATI: log_nirdizati
DIR_LOG_PREFIX: log_prefix # Directory with prefixes obtained
DIR_LOG_STATS: log_stats # Directory with log stats
DIR_MODELS_RESULTS: results_models # Directory with predictive models results
DIR_EXCLUDE: log_exclude # Directory with case_id to be excluded from event-log
FILE_EXCLUDE: case_id_exclude.txt # File with case_id to be excluded from event-log

# MODELS DUMP
DIR_MODELS_DUMP: models_dump # Binary files of prediction models

# MODELS SHAP
DIR_MODELS_SHAP: models_shap 

# MODELS PLOT
DIR_MODELS_PLOT: results_models_plot # Directory prediction plots

# LLM
DIR_LOG_LLM: log_llm # data obtained from LLM with amount_increase
FILE_LOG_LLM: gu_cases_amount_increase_final.csv # log with amount_increase obtained from LLM

# MODELS CONFIGURATION
DIR_CONFIGURATION: models_config
FILE_CONFIGURATION_ENSEMBLE: config_ensemble.json

# EVENT-LOG COLUMN NAMES
LOG_CASE_ID_NAME: case_id
LOG_EVENT_NAME: event_name
LOG_EVENT_TIMESTAMP_NAME: event_timestamp
LOG_REGION_NAME: tender_region
LOG_AMOUNT_NAME: tender_amount
LOG_TENDER_TYPE_NAME: tender_type
LOG_TENDER_DURATION_NAME: duration_dd # duration in days
LOG_TENDER_DURATION_MS_NAME: duration_ms
LOG_TENDER_DURATION_PARTIAL_NAME: duration_partial_dd
LOG_TENDER_SECTOR_NAME: sector
LOG_TENDER_FRAMEWORK_NAME: framework
LOG_TENDER_CPV_NAME: cpv
LOG_LABEL_NAME: label # the outcome to predict

# EVENT-LOG STATS COLUMN NAMES
LOG_CASE_ID_LEN: case_id_length

# PREFIXES
PREFIXES_MIN_NUM: 1 # included
PREFIXES_MAX_NUM: 12 # excluded
PREFIXES_STEP_NUM: 2

# REGRESSION MODELS
RFR_SUFFIX: RFR # RandomForestRegressor
XGR_SUFFIX: XGR # XGBoostRegressor
CV_FOLDS_NUM: 5 # cross-validation folds number
COL_ORDER_METRIC: RMSE_ht

# CSV
CSV_DEFAULT_SEPARATOR: ; 

# FILE STATS (PREFIX)
FILE_PREFIX_STATS: _PREFIX_stats.csv # Prefix statistics file

# MODEL DUMPS
MODEL_DUMP: 1 # 0: no, 1: yes

# APP-LOG
APP_LOG_HEADER:
  - script_name
  - model
  - configuration
  - start_time
  - end_time
  - delta_time
APP_LOG_DIC:
  script_name: None
  model: None
  configuration: None
  start_time: None
  end_time: None
  delta_time: None
DIR_APP_LOG: app_log # application log directory
FILE_APP_LOG: app_log.csv  # application log file

# LSTM
EPOCHS_NUM: 200
OPTIMIZER_NAME: adam
LOSS_NAME: mse